In [ ]:
import fanc

In [ ]:
# https://github.com/htem/FANC_auto_recon for information on api key. Paste yours below or in ./data/fanc_api_key.txt 
api_key = "your api key here"
if api_key == "your api key here":
    with open("./data/fanc_api_key.txt", "r", encoding="utf-8") as f:
        api_key = f.read().strip()
fanc.save_cave_credentials(api_key)

In [3]:
from datetime import datetime, timezone
now = datetime.utcnow()

homepage_neuron_segid = 648518346475400628
# This should give 648518346486614449 as of July 30, 2023
print('Homepage neuron segid:', homepage_neuron_segid)

# Look up the entry in the soma table for this neuron
homepage_neuron_soma = fanc.lookup.soma_from_segid(homepage_neuron_segid, timestamp=now)
print('Homepage neuron soma info:')
homepage_neuron_soma

Homepage neuron segid: 648518346475400628

Using non-pandas query execution is deprecated as it can mangle types, please upgrade caveclient to >=8.0.0 to use pandas for improved type handling.

Homepage neuron soma info:

Empty DataFrame
Columns: [id, created, valid, target_id, id_ref, created_ref, valid_ref, volume, pt_supervoxel_id, pt_root_id, pt_position, bb_start_position, bb_end_position]
Index: []

In [ ]:
# Show a 3D render of the neuron aligned to the template space, with FANC outlines displayed
# Note that `template_space='JRC2018_VNC_FEMALE'` is the default behavior, just specifying it here for clarity
fanc.plot_neurons(homepage_neuron_segid, show_outlines=True, template_space='JRC2018_VNC_FEMALE')

# You can skip warping into alignment with the template if you haven't set up elastix:
#fanc.plot_neurons(homepage_neuron_segid, show_outlines=True, template_space=None)

In [ ]:
# Check the docstring for many more options
fanc.plot_neurons

In [ ]:
# which might lead you to notice the `save` option, which can
# be used to save publication-ready images of your neurons
fanc.plot_neurons(homepage_neuron_segid,
                  show_outlines=True,
                  template_space='JRC2018_VNC_FEMALE',
                  save=True,
                  save_path=f'./output/plot_neuron_{homepage_neuron_segid}.png')

In [4]:
# The following is a simpler alternative to `client = CAVEclient('fanc_production_mar2021')`
client = fanc.get_caveclient()

In [8]:
mdn_segids = fanc.lookup.cells_annotated_with('MDN')
segid = mdn_segids[3]

outputs = client.materialize.synapse_query(pre_ids=segid)
inputs = client.materialize.synapse_query(post_ids=segid)

fanc.statebuilder.render_scene(neurons=segid, annotations=[{'type': 'points', 'name': 'inputs', 'data': inputs.pre_pt_position.values}, {'type': 'points', 'name': 'outputs', 'data': outputs.post_pt_position.values}], bg_color='w')

WARNING:root:Deprecation: this method is to facilitate beta testing of this feature, it will likely get removed in future versions.
WARNING:root:Deprecation: this method is to facilitate beta testing of this feature, it will likely get removed in future versions.
WARNING:root:Deprecation: this method is to facilitate beta testing of this feature, it will likely get removed in future versions.

'https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/4635592140783616'

In [4]:
from datetime import datetime, timezone
now = datetime.utcnow()

homepage_neuron_segid = 
# This should give 648518346486614449 as of July 30, 2023
print('Homepage neuron segid:', homepage_neuron_segid)

# Look up the entry in the soma table for this neuron
homepage_neuron_soma = fanc.lookup.soma_from_segid(homepage_neuron_segid, timestamp=now)
print('Homepage neuron soma info:')
homepage_neuron_soma

Homepage neuron segid: 648518346486614449
Homepage neuron soma info:

,id,created,valid,target_id,id_ref,created_ref,valid_ref,volume,pt_supervoxel_id,pt_root_id,pt_position,bb_start_position,bb_end_position
13915,72763481576702247,2022-12-19 14:40:31.553536+00:00,t,72763481576702247,72763481576702247,2022-12-04 01:46:33.986620+00:00,t,109.196698,73539806579642013,648518346486614449,"[43232, 134024, 4218]","[42416.0, 133360.0, 4163.0]","[44048.0, 134688.0, 4274.0]"

In [ ]:
from neuprint import Client, fetch_neurons, fetch_synapses
c = Client('https://neuprint.janelia.org', dataset='hemibrain:v1.2')

synapses = fetch_synapses(10339, partner=10300)
synapses.plot3d()